# @time 2022/1/17 11:38
# @Author howell
# @File create_code.PY
from test_workplace.smj.smj_utils import *


def create_code():
    # add_code("get", "goods_list")
    # add_code("post", "add_lessen")
    # add_code("post", "detail_lessen")
    # add_code("get", "lessen_list")
    # add_code("post", "edit_lessen")
    # add_code("post", "del_lessen")
    # add_code("get", "raffle_list")
    # add_code("post", "edit_rules")
    # add_code("get", "raffle_detail")
    # add_code("post", "add_raffle")
    # add_code("post", "edit_raffle")
    # add_code("post", "edit_raffle_status")
    # add_code("post", "del_raffle")
    # add_code("get", "prize_list")
    # add_code("get", "prize_detail")
    # add_code("post", "add_prize")
    # add_code("post", "edit_prize")
    # add_code("post", "del_prize")
    # add_code("get", "record_list")
    # add_code("get", "prize_express")
    # add_code("post", "add_goods")
    # add_code("post", "add_channel")
    # add_code("post", "warehouse_edit_stock")
    # add_code("get", "content_list")
    # add_code("get", "content_detail")
    # add_code("post", "add_content")
    # add_code("post", "edit_content")
    # add_code("post", "set_content")
    # add_code("post", "del_content")
    # add_code("get", "author_list")
    # add_code("post", "add_author")
    # add_code("post", "edit_author")
    # add_code("post", "set_author")
    # add_code("post", "del_author")
    # add_code("get", "all_open_author")
    # add_code("post", "add_score_goods")
    # add_code("get", "score_goods_list")
    # add_code("get", "attr_list")
    # add_code("post", "add_shop_account")
    # add_code("post", "add_offline_goods")
    # add_code("post", "set_config_gift_card")
    # 门店端
    add_code("post", "edit_business_at")
    add_code("post", "edit_navigation")
    add_code("post", "edit_offline_notice")
    add_code("post", "edit_contact_phone")
    add_code("post", "edit_shop_imgs")
    add_code("get", "my_list")
    add_code("post", "order_preview")
    add_code("post", "edit_shop_name")
    add_code("post", "order_use_c")
    add_code("get", "order_use_list")
    add_code("get", "my_goods_offline")
    add_code("get", "goods_detail")
    add_code("get", "order_list_offline")
    add_code("get", "order_detail")
    add_code("get", "index_statistics")
    add_code("get", "shop_offline_detail")
    add_code("get", "shop_offline_detail_setting")
    add_code("get", "shop_account_sub_list")
    add_code("post", "add_sub_account")
    add_code("post", "edit_sub_account")
    add_code("post", "shop_capital_record")


if __name__ == '__main__':
    create_code()
